### ISSUE TITLE
Path to the styles file.

### ISSUE THREAD

**Issue by dmazaleuskaya** [Pavel-Yarakhovich/lotos#2]
https://github.com/Pavel-Yarakhovich/lotos/blob/aa10c61f5bd7307f793801a666062894b04fba06/index-desktop-1.html#L11

According to the path written in the  '.htm'l file, stylesheet should be located in the `css` folder. I mean the project in git should have completely the same structure as locally so that I can clone it and start working at once.

**Comment by Pavel-Yarakhovich** [comment]
Solved
